sudo: required
services:
  - docker 
before_install:
  - docker build -t subodh15/deockerreact:latest -f Dockerfile.dev .
script:
  - docker run subodh15/deockerreact:latest npm run test -- --coverage